build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            image: default-bionic
            environment:
                php: 8.1.2
            tests:
                override:
                    - php ./vendor/bin/phpunit --configuration phpunit.xml --testsuite scrutinizer
                    - php-scrutinizer-run
checks:
    php: true
coding_style:
    php:
        spaces:
            within:
                brackets: true
filter: {  }
