name: FoodHut Unit Tests

on:
  push:
  pull_request:

jobs:
  syntax_errors:
    name: "Syntax errors"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
          tools: "parallel-lint"
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Validate Composer configuration"
        run: "composer validate --strict"
      - name: "Check source code for syntax errors"
        run: "composer exec -- parallel-lint app/ routes/ lang/ database/ tests/"
  unit_tests:
    name: "Unit Tests"
    needs:
      - "syntax_errors"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.4.27
        env:
          MARIADB_ROOT_PASSWORD: 12345678
          MARIADB_DATABASE: foodhut
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extension-csv: mbstring, bcmath
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate Key
        run: php artisan key:generate
      - name: Run migrations and Execute tests
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: 12345678
          DB_DATABASE: foodhut
        run: |
          php artisan migrate --seed
          php artisan test
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/php@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --all-projects
      #     command: test
  deploy-production:
    name: Deploy Project to PRODUCTION Server
    runs-on: ubuntu-latest
    needs: [unit_tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        env:
            DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
            PAT: ${{ secrets.PAT }}
            DEPLOY_PATH_PRODUCTION: ${{ secrets.DEPLOY_PATH_PRODUCTION }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOT_ENV, PAT, DEPLOY_PATH_PRODUCTION
          script: |
            sudo mkdir -p /tmp/production/foodhut
            sudo chmod -R 777 /tmp/production/foodhut
            cd /tmp/production && git clone https://$PAT@github.com/ikechukwukalu/foodhut.git
            cd /tmp/production/foodhut
            sudo git checkout main
            sudo touch .env
            echo "$DOT_ENV" | sudo tee /tmp/production/foodhut/.env
            composer install
            sudo php artisan migrate --force
            sudo php artisan config:clear
            sudo rm -r $DEPLOY_PATH_PRODUCTION/foodhut-old
            sudo mv $DEPLOY_PATH_PRODUCTION/foodhut $DEPLOY_PATH_PRODUCTION/foodhut-old
            sudo mkdir -p $DEPLOY_PATH_PRODUCTION/foodhut
            sudo cp -r /tmp/production/foodhut/* $DEPLOY_PATH_PRODUCTION/foodhut
            sudo rm -r /tmp/production/foodhut
            echo "$DOT_ENV" | sudo tee $DEPLOY_PATH_PRODUCTION/foodhut/.env
            sudo chmod -R 0755 $DEPLOY_PATH_PRODUCTION/foodhut
            sudo chmod -R 777 $DEPLOY_PATH_PRODUCTION/foodhut/storage
